### ISSUE TITLE
Href generator button?

### ISSUE THREAD

**Issue by tunesmith** [taglia/rb_upgrade_planner#6]
I'm not immediately sure how to do it myself, but I think it would be great if the page had an href generator button.  I know the code for a build can somehow be appended to the query string, but I'm not sure how.  But if a build could be "copied as link" somehow, it would make discussion a lot easier on the subreddit.

**Comment by taglia** [comment]
It would be just a matter of copying appending what is currently already generated in the Textarea to "http://rb.shm.me/?s=", but I agree it can be useful to have the link ready. I have added another area at the bottom where you can generate the direct link; it's quite ugly but it works.
